buiding a new body for conflict reponses
sigstore/scaffolding pull request #1068
Opened 2024-04-18 17:36 UTC by javanlacerda

Closes #900

#### Summary

It adds retries updating the body for Rekor writing requests when the response has 409 code. It means that the body has conflict, then we should create a new/different body for the request.

#### Release Note

#### Documentation

2024-04-18 17:37 UTC, javanlacerda commented on cmd/prober/write.go
> +	for resp.StatusCode == http.StatusConflict {
Does it make sense it be in a `while`? Or should I set a number of attempts ?

2024-04-23 06:51 UTC, haydentherapper requested changes

2024-04-23 06:51 UTC, haydentherapper commented on cmd/prober/write.go
> +	latency := time.Since(t).Milliseconds()
Can we record latency and response data for each request to Rekor? This would measure the total time for all requests.

2024-04-23 06:51 UTC, haydentherapper commented on cmd/prober/write.go
> +	for {
Can we put a reasonable limit, let's say 10, on this loop?

2024-04-23 06:51 UTC, haydentherapper commented on cmd/prober/write.go
> +	resp, t, err := makeRekorRequest(cert, priv, hostPath)
Can we move this into the for loop?

2024-04-23 06:51 UTC, haydentherapper commented on cmd/prober/write.go
> +	return resp, t, err
I'd suggest returning the latency calculation `latency := time.Since(t).Milliseconds()` rather than the time object.

2024-04-25 17:34 UTC, haydentherapper approved these changes
Thanks!

2024-04-25 17:39 UTC, merged